TG-23 reate getAll - getById Routes & Controllers for Task
BaSP-m2022/alfonso-trackgenix-server pull request #13
Opened 2022-05-13 22:16 UTC by vadalamati

2022-05-14 03:07 UTC, JuanMornik requested changes

2022-05-14 03:07 UTC, JuanMornik commented on src/controllers/tasks.js
> +    res.status(200).json(allTasks);
Fijate de mantener el formato que está en la página 4 de la problemática:   

```
 res.status(x00).json({
       message: "string",
       data: { } || [ ] || undefined,
       error: boolean
   })
```

Tener en cuenta esto en todas las respuestas de las request ( líneas 10, 19, 21 y 26 )

2022-05-14 03:07 UTC, JuanMornik commented on src/routes/tasks.js
> +router.get('/id', tasksControllers.getTasksById);
El primer parámetro debe ser '/:id'

2022-05-14 20:04 UTC, vadalamati commented on src/controllers/tasks.js
> +import { models } from 'mongoose';
Jejeje ahí lo cambio. Gracias!!!!

2022-05-14 20:23 UTC, vadalamati commented on src/controllers/tasks.js
> +    res.status(200).json(allTasks);
Perfecto! Ya pushee los cambios a la branch. Gracias!!

2022-05-14 20:23 UTC, vadalamati commented on src/routes/tasks.js
> +router.get('/id', tasksControllers.getTasksById);
Si, se me pasó y no me di cuenta. Cambio hecho y pusheado. Gracias, Juani!

2022-05-16 14:25 UTC, HiginiaMed reviewed
Fijate que el archivo index.js de la carpeta router no lo tenes actualizado.

2022-05-17 21:46 UTC, AlfonsoDalix approved these changes
Good job

2022-05-17 21:46 UTC, merged