TG-16 Employee model
BaSP-m2022/alfonso-trackgenix-server pull request #14
Opened 2022-05-13 22:47 UTC by SebastianRonchetti

2022-05-14 01:45 UTC, JuanMornik requested changes

2022-05-14 01:45 UTC, JuanMornik commented on src/models/employee.js
> +const Schem = mongoose.Schema;
A mi me tira error el eslint si lo pongo así. Me obliga a ponerlo { Schem } = mongoose. Yo te recomiendo que te fijes si tenés habilitada la extensión de eslint

2022-05-14 01:45 UTC, JuanMornik commented on src/models/employee.js
> +import mongoose from 'mongoose';
Te dejo el comentario acá porque en el nombre no me deja. Fijate que en la problemática pide que el nombre del archivo empiece con mayúscula, por ende sería: 'Employee.js'

2022-05-14 03:27 UTC, SebastianRonchetti commented on src/models/employee.js
> +const Schem = mongoose.Schema;
A mi me tiró la misma corrección pero cuando le puse Schem en vez de Schema no me la tiró más, pero si sigue estando la pongo como decís nomás.

2022-05-14 17:47 UTC, AlfonsoDalix requested changes

2022-05-14 17:47 UTC, AlfonsoDalix commented on src/models/EmployeeModel.js
> +    },
I'd change it for first name, and last name

2022-05-14 19:10 UTC, SebastianRonchetti commented on src/models/EmployeeModel.js
> +    },
Done, also changed min > minlenght since min was for numeric values

2022-05-14 19:29 UTC, Javier-Cervera reviewed
I think there's no need to change file names. Such as:
employeeControllers --> employee
EmployeeModel --> model
Because the paths are self-referential

2022-05-14 21:07 UTC, AlfonsoDalix requested changes

2022-05-14 21:07 UTC, AlfonsoDalix commented on .gitignore
> +./index
Do not change any lines in the .gitignore file

2022-05-14 21:07 UTC, AlfonsoDalix commented on src/models/employee.js
> +    },
We could add an enum here like enum:['male', 'female', 'other']

2022-05-14 21:07 UTC, AlfonsoDalix commented on src/models/EmployeeModel.js
> +export default mongoose.model('Employee', employeeSchema);
If we have other document with the same name and lines, delete this file

2022-05-14 21:07 UTC, AlfonsoDalix commented on src/controllers/employeeControllers.js
> +export default router;
We have to do it in a separate ticket

2022-05-14 21:31 UTC, SebastianRonchetti commented on .gitignore
> +./index
I had started working on the next ticket and added them to ignore the recent changes without having to delete everything

2022-05-14 21:38 UTC, SebastianRonchetti commented on src/models/EmployeeModel.js
> +export default mongoose.model('Employee', employeeSchema);
Some mixup happened with the other branch I was woking on

2022-05-14 21:45 UTC, SebastianRonchetti commented on src/controllers/employeeControllers.js
> +export default router;
Yes, some mixup happened with the git console as I was already working on a new ticket, some errors were thrown and I thought I solved it. 
Evidently I was wrong

2022-05-14 21:50 UTC, SebastianRonchetti commented on src/models/employee.js
> +    },
Done

2022-05-15 00:26 UTC, AlfonsoDalix approved these changes

2022-05-15 00:26 UTC, merged