TG-37
BaSP-m2022/alfonso-trackgenix-server pull request #16
Opened 2022-05-14 00:03 UTC by vadalamati

2022-05-14 02:48 UTC, JuanMornik requested changes

2022-05-14 02:48 UTC, JuanMornik commented on src/routes/projects.js
> +router.get('/id', projectsControllers.getProjectById);
te faltó " : " en la linea 7. Sería '/:id'

2022-05-14 03:30 UTC, JuanMornik submitted a review, later dismissed

2022-05-14 03:30 UTC, JuanMornik commented on src/controllers/projects.js
> +    res.status(200).json(allProjects);
Fijate de mantener el formato que está en la página 4 de la problemática:

```
res.status(x00).json({
  message: "string",
  data: { } || [ ] || undefined,
  error: boolean
})
```

Tener en cuenta esto en todas las respuestas de las request ( líneas 9, 19, 21 y 26 )

2022-05-14 20:36 UTC, vadalamati commented on src/controllers/projects.js
> +import { models } from 'mongoose';
Listo, chicos! Ahí lo cambié. Es el mismo error de tipeo que en la otra PR. Gracias!!! se me paso :(

2022-05-14 20:37 UTC, vadalamati commented on src/routes/projects.js
> +router.get('/id', projectsControllers.getProjectById);
Listo! Ahí lo arregle. Gracias!!

2022-05-14 20:42 UTC, vadalamati commented on src/controllers/projects.js
> +    res.status(200).json(allProjects);
Listo!! Corregidos los cambios y pusheados. Gracias!!!

2022-05-15 07:09 UTC, Javier-Cervera commented on src/controllers/projects.js
> +import models from '../models/projects.json';
We should change the path to `'../models/Projects'` because the JSON is going to be deleted.
Also, I think we have 2 options for import and use:
- `import models from '../models/';` --> and then `const allProjects = await models.Projects.find({});`
This way all models will be imported
or
- `import projectModel from '../models/Projects';` --> `const allProjects = await projectModel.find({});`
and only the specific model will be imported.

2022-05-15 07:09 UTC, Javier-Cervera commented on src/controllers/projects.js
> +      message: 'Internal server error',
We could use `message: error.details[0].message` when `(error)` is defined

2022-05-15 07:09 UTC, Javier-Cervera commented on src/controllers/projects.js
> +      const project = await models.Project.findById(req.params.id);
Same as above

2022-05-15 07:09 UTC, Javier-Cervera commented on src/controllers/projects.js
> +      message: 'Internal server error',
Same as above

2022-05-16 23:41 UTC, AlfonsoDalix approved these changes

2022-05-16 23:42 UTC, merged