TG-28: Project model created
BaSP-m2022/alfonso-trackgenix-server pull request #18
Opened 2022-05-14 01:34 UTC by JuanMornik

2022-05-14 03:07 UTC, Javier-Cervera commented on src/models/Projects.js
> +
Spaces between elements wouldn't be necessary.

2022-05-14 03:07 UTC, Javier-Cervera reviewed
Looks good to me

2022-05-14 03:09 UTC, Javier-Cervera commented on src/models/Projects.js
> +
Spaces between elements wouldn't be necessary.

2022-05-14 03:56 UTC, SebastianRonchetti commented on src/models/Projects.js
> +    ],
Projects should have tasks assigned so perhaps a similar array could be made in a comment to express said link

2022-05-14 18:37 UTC, AlfonsoDalix requested changes

2022-05-14 18:37 UTC, AlfonsoDalix commented on src/models/Projects.js
> +    }, */
Descamoentemos esto y le podemos pasar que sea de tipo String

2022-05-14 18:37 UTC, AlfonsoDalix commented on src/models/Projects.js
> +        role: { type: String, required: true },
el role lo podemos hacer de tipo string y le pasamos el enum de opciones como:
enum: ['DEV', 'QA', 'PM', 'TL']

2022-05-14 18:37 UTC, AlfonsoDalix commented on src/models/Projects.js
> +      {
Deberíamos agregar tambien un id: usemos tipo String y required

2022-05-15 00:24 UTC, AlfonsoDalix approved these changes

2022-05-15 00:24 UTC, merged