TG-24: Time sheets model
BaSP-m2022/alfonso-trackgenix-server pull request #20
Opened 2022-05-14 04:19 UTC by GonzaloBracamonte

2022-05-14 16:14 UTC, Javier-Cervera commented on src/models/Time-sheets.js
> +    required: true,
Maybe we could use `type: mongoose.Schema.Types.ObjectId`, and next week add `ref: 'Employees'`

2022-05-14 16:34 UTC, GonzaloBracamonte commented on src/models/Time-sheets.js
> +    type: String,
It could be, now I will change it

2022-05-14 16:34 UTC, GonzaloBracamonte commented on src/models/Time-sheets.js
> +    required: true,
You´re right, i will change this too

2022-05-14 18:24 UTC, AlfonsoDalix requested changes

2022-05-14 18:24 UTC, AlfonsoDalix commented on src/models/Time-sheets.js
> +    type: mongoose.Schema.Types.ObjectId,
Por ahora dejemoslo como un String, ya que no vamos a relacionarlos

2022-05-14 19:49 UTC, Javier-Cervera commented on src/models/Time-sheets.js
> +  },
We could add a property `enum: ['DEV', 'QA', 'PM', 'TL']`

2022-05-15 00:23 UTC, AlfonsoDalix commented on src/models/Time-sheets.js
> +  role: {
role te tendría que quedar así
role: {
    type: String,
    enum: ['DEV', 'QA', 'PM', 'TL'],
    required: true,
}

2022-05-15 14:30 UTC, AlfonsoDalix approved these changes

2022-05-15 14:30 UTC, merged