TG-41: Add seeds
BaSP-m2022/alfonso-trackgenix-server pull request #40
Opened 2022-05-20 22:23 UTC by vadalamati

2022-05-21 01:16 UTC, Javier-Cervera requested changes

2022-05-21 01:16 UTC, Javier-Cervera commented on src/seeds/employees-seed.js
> +  lastName: 'test',
lastName has a different name in the Employee model. It's called `surname`

2022-05-21 01:52 UTC, vadalamati commented on src/seeds/employees-seed.js
> +  lastName: 'test',
Corrected, thanks!!!!

2022-05-21 01:52 UTC, vadalamati commented on src/seeds/projects-seed.js
> +  startDate: '20/05/2022',
solved, thanks!!!

2022-05-21 22:22 UTC, Javier-Cervera submitted a review, later dismissed

2022-05-22 20:13 UTC, AlfonsoDalix approved these changes

2022-05-22 20:14 UTC, merged